spring:
  application:
    name: high-like
  mvc:
    servlet:
      path: /api
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/high_like?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
  data:
    # Redis 配置
    redis:
      database: 0
      host: localhost
      timeout: 5000
      port: 6379

# 整合 Prometheus + Grafana
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus # 开启 prometheus 指标
  metrics:
    distribution:
      percentiles:
        http:
          server:
            requests: 0.5, 0.75, 0.9, 0.95, 0.99

# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
  enable: true
  setting:
    language: zh_cn